approvedGitRepositories:
  - '**'

enableScripts: true

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?

nodeLinker: node-modules

npmMinimalAgeGate: 0
npmPreapprovedPackages:
  - '@glitchbars/prisma-schemas'

npmScopes:
  glitchbars:
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
