approvedGitRepositories:
  - '**'

enableScripts: true

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  glitchbars:
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'
